spring.application.name=VanOpt

# DATABASE CONNECTION
spring.datasource.url=jdbc:mysql://localhost:3306/vanopt
spring.datasource.username=root
spring.datasource.password=tErminatori5&*

# MYSQL DRIVER
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# FLYWAY
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration